name: audio-sharing # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: audio-sharing
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  audio-sharing:
    after: [rustup]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/World/AudioSharing.git
    source-depth: 1
    source-tag: '0.2.2'
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    meson-parameters:
      - --prefix=/snap/audio-sharing/current/usr
    build-packages:
      - libelf-dev
      - libgstrtspserver-1.0-dev
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/audio-sharing.patch
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/audio-sharing/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    parse-info: [ usr/share/metainfo/de.haeckerfelix.AudioSharing.metainfo.xml ]
    organize:
      snap/audio-sharing/current: .
  deps:
    plugin: nil
    after: [ audio-sharing ]
    stage-packages:
      - libgstrtspserver-1.0-0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstrtspserver-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstrtspserver-1.0.so.0.2001.0
slots:
  audio-sharing:
    interface: dbus
    bus: session
    name: de.haeckerfelix.AudioSharing
apps:
  audio-sharing:
    command: usr/bin/audio-sharing
    common-id: de.haeckerfelix.AudioSharing
    extensions: [gnome]
    plugs:
      - audio-playback
      - network
